### ISSUE TITLE
Intl translations for error messages stops to work

### ISSUE THREAD

**Issue by mcjmigdal** [simplabs/ember-validated-form-buffer#121]
Hi!
I've noticed that when using your addon intl translations for error messages stops to work. Is there some way to overcome this issue? Have anyone had similar problem?
Cheers MM

**Comment by marcoow** [comment]
Do you have any more specific information like an actual error you're seeing, details on your setup etc.?

**Comment by mcjmigdal** [comment]
Hi,
for validation / translations I'm using:
```
ember-intl,
ember-cp-validations,
@ember-intl/cp-validations,
ember-bootstrap-cp-validations,
ember-validated-form-buffer
````

there is no error message. All translations works perfectly except for validation errors. If I remove `ember-validated-form-buffer` and restart the app translation of validation errors start to work again. I'll try to make an example over weekend.

**Comment by mcjmigdal** [comment]
I've changed order of addons in package.json such that  `ember-validated-form-buffer`
 go before `@ember-intl/cp-validations` and it works.
I'm closing issue.
